parameters:
  - name: appVersion
    displayName: Update version of app
    type: string
    default: 2.4.0-beta
    values:
      - 2.4.0-beta

name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

schedules:
  - cron: "0 3 * * 1"
    displayName: Publish Android App
    branches:
      include:
        - main

pool:
  vmImage: 'macos-latest'

variables:
- group: AdaptiveCards-KVLink