parameters:
  - name: appVersion
    displayName: Update version of app
    type: string
    default: 2.4.0-beta
    values:
      - 2.4.0-beta

name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

schedules:
  - cron: "0 3 * * 1"
    displayName: Publish Android App
    branches:
      include:
        - main

pool:
  vmImage: 'macos-latest'

variables:
- group: AdaptiveCards-KVLink

steps:
- task: Gradle@2
  displayName: 'gradlew mobile:assembleRelease'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'mobile:assembleRelease'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: '/keystore'
    apksignerKeystorePassword: '$(keystorePwd)'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: '$(keystorePwd)'
    
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'AppCenter App'
    appSlug: 'AdaptiveCards-Mobile/AdaptiveCards-iOS-Visualizer'
    appFile: 'source/android/mobile/release/'
    buildVersion: '${{ parameters.appVersion }}'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New build'
    destinationType: 'groups'
    